http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/POR.png
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/BKN.png
http://cdn.clicktale.net/www/XHRWrapper.js
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/CHA.png
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/main.default.js
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/ATL.png
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/ORL.png
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/MIN.png
http://cdn.optimizely.com/js/3717650865.js
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/BOS.png
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/MIA.png
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/MEM.png
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/OKC.png
http://tpc.googlesyndication.com/safeframe/1-0-5/html/container.html
http://cdn.taboola.com/libtrc/static/thumbnails/3aadbb71016ecd7a194bbe2791777e9a.png
http://www.cbssports.com/
http://mtrx.go.sonobi.com/morpheus.cbssports.1044.js
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js/main-lite.mobile.js
http://www.googletagservices.com/tag/js/gpt.js
http://sports.cbsimg.net/fonts/proxima-nova/extra-bold/webfont.woff2
http://sportsfly.cbsistatic.com/bundles/sportsmediacss/images/core/cbssports-digital-logo.svg
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediacss/css/main.mobile.css
http://sportsfly.cbsistatic.com/bundles/sportsmediacss/images/core/footer_golfweb.svg
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediacss/css/header-footer/saag/saag.mobile.css
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/fly/utils/data-prefix-1.0.js
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/managers/ad.js
http://sports.cbsimg.net/fonts/proxima-nova/semi-bold-condensed/webfont.woff2
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/DET.png
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/libs/components-lite.js
http://segment-data.zqtk.net/cbsi-a7d9c2?url=http%3A%2F%2Fwww.cbssports.com%2F
http://js-sec.indexww.com/ht/ls-proximic.js
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/managers/components-lite.mobile.js
http://sportsfly.cbsistatic.com/bundles/sportsmediacss/images/fonts/icon-moon/icon-moon.woff2?3415gs
http://sports.cbsimg.net/fonts/proxima-nova/regular/webfont.woff2
http://sports.cbsimg.net/fonts/proxima-nova/light/webfont.woff2
http://sportshub.cbsistatic.com/i/r/2017/01/14/d70b2cc2-f225-4967-a38d-ed3695881940/thumbnail/325x183/b3c608731772f29fc2685b6b5a303f82/thomas-rawls.jpg
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/SAC.png
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/fly/components/base-1.0.js
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/HOU.png
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/PHI.png
http://sportsfly.cbsistatic.com/bundles/sportsmediacss/images/core/commissioner-button1.svg
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/libs/require-2.1.22.js
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/fly/libs/jquery.widget-1.9.2.js
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/fly/libs/guid-1.0.js
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/TOR.png
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/CLE.png
http://sportshub.cbsistatic.com/i/r/2017/01/14/051cfd5e-4d21-41ff-b71d-d7d1d8974c5b/thumbnail/450x253/77afa5753d9fed6d9ed8295b2679cb20/clowney-and-mercilus.jpg
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediacss/css/header-footer/header-footer.mobile.css
http://sportsfly.cbsistatic.com/bundles/sportsmediacss/images/core/commissioner-button2.svg
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/jquery.js
http://sports.cbsimg.net/fonts/proxima-nova/semi-bold/webfont.woff2
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediacss/css/icon-moon/icon-moon.css
http://sportsfly.cbsistatic.com/fly-493/bundles/sportsmediajs/js-build/main.mobile.js
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/MIL.png
http://sports.cbsimg.net/images/nba/logos/90x90/scoreboard/UTA.png
http://sportshub.cbsistatic.com/i/r/2017/01/12/94535136-0d02-46ea-8d3f-1eedf69d58a0/thumbnail/100x100/15a0a56aef465a88f9449933ea15d6d0/chiefs-steelers.jpg
http://sports.cbsimg.net/fonts/proxima-nova/bold/webfont.woff2
http://sportshub.cbsistatic.com/i/r/2017/01/14/50dc7d06-3505-4b36-b6de-6c5388ac58f9/thumbnail/325x183/71f03ce695771e714c0a0b148075209f/tom-brady.jpg
