https://rf15.chase.com/activity?_o=15629&_t=corp_wl_dynamicad&ssv_transid=312da19a-67621496-3dc31675-369c83c6&ssv_random=485&ssv_adcontext=tripletLinkId:default;tripletImageId:default;tripletProductTitleId:default;tripletCopyTextId:default;tripletCallToActionId:default;tripletAlignmentId:default&ssv_placement=chasehome_3/trip1
https://www.chase.com/c/121316/etc/designs/chase-ux/css/fonts/smc.ttf
https://sites.chase.com/content/Creatives/Public/Triplets/2016/Card/Multi-Card/47007_comparecardstrip353964.dynamic.html
https://www.chase.com/content/chase-ux/en/structured/module/adtriplet/primary-triplet/_jcr_content/module.html
https://www.chase.com/content/chase-ux/en/structured/module/geoimage/ad-geo/_jcr_content/module.html
https://mfasa.chase.com/auth/js/device.js
https://mfasa.chase.com/auth/js/json.js
https://sites.chase.com/content/services/structured-image/image.mobile.png/XCRT/Triplets/2016/Retail/A47962_IC1980_Retail_Public_Offers_Triplet_384x216.png
https://www.chase.com/
https://rf15.chase.com/activity?_o=15629&_t=corp_wl_viewimpression&ssv_transid=312da19a-67621496-3dc31675-369c83c6&ssv_random=485&ssv_placement=chasehome_3/hero&ssv_creativeid=65445697
https://rf15.chase.com/activity?_o=15629&_t=corp_wl_dynamicad&ssv_transid=312da19a-67621496-3dc31675-369c83c6&ssv_random=485&ssv_adcontext=tripletLinkId:default;tripletImageId:default;tripletProductTitleId:default;tripletCopyTextId:default;tripletCallToActionId:default;tripletAlignmentId:default&ssv_placement=chasehome_3/trip2
https://www.chase.com/c/121316/etc/designs/chase-ux/css/blue-ui.min.css
https://sites.chase.com/content/services/structured-image/image.mobile.jpg/XCRT/Triplets/2016/Card/Sapphire/A47480_IC1909_Card_Acq_Sapphire_Triplet_384x216.jpg
https://www.chase.com/apps/chase/clientlibs/foundation/tagmanagerextensions.js
https://www.chase.com/c/121316/etc/designs/chase-ux/css/fonts/opensans-semibold.woff
https://www.chase.com/c/121316/etc/designs/chase-ux/css/img/choices-logo-blue_lite.png
https://sites.chase.com/content/Creatives/Public/Heroes/Auto/47101_flextemp_autodirecthero354441.dynamic.html
https://sites.chase.com/content/Creatives/Public/Triplets/2016/Retail/47962_q4_checkinghptripletcwo201.dynamic.html
https://www.chase.com/apps/chase/clientlibs/foundation/scripts/Personalization.js
https://www.chase.com/c/121316/etc/designs/chase-ux/css/site.min.css
https://sites.chase.com/content/Creatives/Public/Triplets/2016/Card/Sapphire/47480_sapphireprefm2355135.dynamic.html
https://www.chase.com/c/121316/etc/designs/chase-ux/css/fonts/opensans-light.woff
https://sites.chase.com/content/services/structured-image/image.mobile-portrait.jpg/XCRT/Flexible-Templates/Hero/47101_FlexTemp_IC1822_CAD_Hero_Retina_2560x1440_BTN.jpg
https://sites.chase.com/apps/campaignmanagement/clientlibs/slotplacement/js/slotplacement.min.js
https://www.chase.com/c/121316/etc/designs/chase-ux/css/img/EHL-Slice.png
https://rf15.chase.com/activity?_o=15629&_t=corp_wl_dynamicad&ssv_transid=312da19a-67621496-3dc31675-369c83c6&ssv_random=485&ssv_adcontext=tripletLinkId:default;tripletImageId:default;tripletProductTitleId:default;tripletCopyTextId:default;tripletCallToActionId:default;tripletAlignmentId:default&ssv_placement=chasehome_3/trip3
https://www.chase.com/c/121316/etc/designs/chase-ux/clientlibs/require/js/require.min.js
https://sites.chase.com/content/services/structured-image/image.mobile.jpg/XCRT/Triplets/2016/Card/Multi-Card/A47007_WO353964-IC1420_Compare_Triplet_Desktop_Freedom_Unl_384x216.jpg
https://mfasa.chase.com/auth/alogin.jsp
https://www.chase.com/c/121316/etc/designs/chase-ux/clientlibs/chase-ux/js/dist/chase-ux.min.js
https://www.chase.com/etc/designs/chase-ux/css/img/checkmark.png
https://ad.doubleclick.net/ad/N5762.547841.VISUALIQINC/B8070268;sz=1x1;u=https://www.chase.com/%7CTAPAD_b27e0081-d8d3-11e6-8482-005056a210b4;ord=[1484393791394]?
https://www.chase.com/etc/chase/appsconfig/clientconfig.js
https://mfasa.chase.com/auth/js/plugin.min.js
https://www.chase.com/content/chase-ux/en/structured/module/carousel/carousel-single-images-10/_jcr_content/module.html
https://mfasa.chase.com/auth/js/jquery-1.9.1.min.js
https://www.chase.com/etc/designs/chase-ux/css/img/ie_alert.png
https://rf15.chase.com/activity?_o=15629&_t=corp_wl_viewimpression&ssv_transid=312da19a-67621496-3dc31675-369c83c6&ssv_random=485&ssv_placement=chasehome_3/trip1&ssv_creativeid=65684419
https://www.chase.com/c/121316/etc/designs/chase-ux/css/fonts/opensans.woff
https://www.chase.com/c/121316/etc/designs/chase-ux/css/fonts/icomoon.ttf?n3bwfv
https://sites.chase.com/services/campaignmanagement/clientconfig.slotplacementconfig.js
https://www.chase.com/c/121316/etc/designs/chase-ux/clientlibs/jquery/js/jquery-1.10.2.min.js
https://www.chase.com/c/121316/etc/designs/chase-ux/clientlibs/modernizr/js/modernizr-2.8.3.min.js
https://www.chase.com/apps/services/tags/https/www.chase.com/
https://rf15.chase.com/activity?_o=15629&_t=corp_wl_dynamicad&ssv_transid=312da19a-67621496-3dc31675-369c83c6&ssv_random=485&ssv_adcontext=heroLinkId:default;heroImageId:default&ssv_placement=chasehome_3/hero
https://www.chase.com/etc/designs/chase-ux/css/img/high-alert-icon.png
https://www.chase.com/c/121316/apps/chase/clientlibs/foundation/scripts/Reporting.js
https://mfasa.chase.com/auth/js/mfp.js
