http://www.google-analytics.com/analytics.js
http://s3.feedly.com/production/head/images/tab-second@2x.png
http://s3.feedly.com/production/head/images/icon-action-overview-100@2x.png
http://fonts.gstatic.com/s/lora/v9/_MYF_5lLoOGnzKiQsUc_vevvDin1pK8aKteLpeZ5c0A.woff2
http://s3.feedly.com/production/head/images/tab-first@2x.png
http://s3.feedly.com/production/head/images/icon-feedly.png
http://feedly.com/
http://s3.feedly.com/web/30.0.1278/js/web-main-bundle.js
http://www.feedly.com/
https://platform.twitter.com/widgets.js
http://fonts.gstatic.com/s/lora/v9/_IxjUs2lbQSu0MyFEAfa7ZBw1xU1rKptJj_0jans920.woff2
http://s3.feedly.com/production/head/images/icon-action-backtotop.png
http://s3.feedly.com/production/head/images/icon-action-overview-6@2x.png
http://s3.feedly.com/production/head/images/icon-action-overview-0@2x.png
http://s3.feedly.com/web/30.0.1278/fx/feedly-fx.css
http://s3.feedly.com/production/head/images/icon-search-44.png
http://s3.feedly.com/web/30.0.1278/js/web-templates-bundle.js
http://s3.feedly.com/production/head/images/icon-action-next.png
http://s3.feedly.com/production/head/images/icon-addshortcut@2x.png
http://s3.feedly.com/production/head/images/icon-editshortcut@2x.png
http://fonts.gstatic.com/s/lora/v9/mlTYdpdDwCepOR2s5kS2CwLUuEpTyoUstqEm5AMlJo4.woff2
http://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js
http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&subset=latin,latin-ext,cyrillic
http://fonts.gstatic.com/s/lora/v9/rAXKWvABQNHjPUk26ixVvvesZW2xOQ-xsNqO47m55DA.woff2
http://s3.feedly.com/production/head/images/icon-action-overview-4@2x.png
http://s3.feedly.com/production/head/images/landing/photo-mit-bw@2x.png
http://s3.feedly.com/production/head/images/icon-action-refresh.png
http://s3.feedly.com/img/oops.png
http://s3.feedly.com/production/head/images/icon-action-customize.png
http://s3.feedly.com/production/head/images/icon-action-markasread.png
http://s3.feedly.com/production/head/images/landing/screenshot-web@2x.png
