http://mobile.reuters.com/
https://api.b2c.com/api/init-1014jx5z9ama1oivudf.js
http://s4.reutersmedia.net/resources_v3/images/win-sprite-media-title-icons-2x.png
http://freegeoip.net/json/
http://s4.reutersmedia.net/resources/r/?m=02&d=20170117&t=2&i=1169093991&w=720&fh=&fw=&ll=&pl=&sq=&r=LYNXMPED0G1JY
http://s4.reutersmedia.net/resources_v3/js/win-sharetools.js
https://www.googletagmanager.com/gtm.js?id=GTM-W9SLGS
http://s3.reutersmedia.net/resources_v3/images/win-ico-video.png
http://s2.reutersmedia.net/resources_v3/images/win-ico-picture.png
https://attribution.report/pixel?appnexus=3773292846233317986&adv_id=mscg&campaign_id=mscg_a
http://s4.reutersmedia.net/resources_v3/images/win-ico-right-arrow.png
http://tags.crwdcntrl.net/c/5155/cc_af.js
https://script.hotjar.com/modules-5d19873aea85cbea800b9bffe46ced81.js
http://s3.reutersmedia.net/resources_v3/js/analytics/win-GTM.js
https://z.moatads.com/reutersdfpcw319687550988/moatad.js
http://connect.facebook.net/en_US/fbevents.js
http://mobile.reuters.com/reuters_winnebago_bootstrap.js
http://s3.reutersmedia.net/resources_v3/js/libraries/win-lib.min.js
http://mobile.reuters.com/resources_v2/fonts/Knowledge-Medium.woff
http://s4.reutersmedia.net/resources_v3/js/win-event.js
http://s4.reutersmedia.net/resources_v3/js/win-utils.js
http://s4.reutersmedia.net/resources_v3/images/video-indicator.png
http://gwiqcdn.globalwebindex.net/gwiq/gwiq.js
http://b.scorecardresearch.com/beacon.js
http://www.googletagservices.com/tag/js/gpt.js
http://mobile.reuters.com/resources_v2/fonts/Knowledge-Light.woff
http://s4.reutersmedia.net/resources_v3/images/win-menu-arrow.png
http://s4.reutersmedia.net/resources_v3/images/win-ico-wire-arrow.png
http://s2.reutersmedia.net/resources_v3/js/win-trending.js
http://s2.reutersmedia.net/resources_v3/images/reuters-logo-win-lrg.png
http://api-54-187-14-58.b2c.com/api/adblock.js
http://s3.reutersmedia.net/resources_v3/js/win-main.js
http://s4.reutersmedia.net/resources_v3/js/win-main-header.js
http://s2.reutersmedia.net/resources_v3/js/win-search.js
http://static.yieldmo.com/icons/af-beta/56ee8cde-9196-4a42-909e-9006ed3790dc.jpg
http://mobile.reuters.com/resources_v2/fonts/Knowledge-Regular.woff
http://s3.reutersmedia.net/resources_v3/images/search-input-icon.png
https://s.yieldmo.com/partner.min.html
http://static.hotjar.com/c/hotjar-339970.js?sv=5
http://static.chartbeat.com/js/chartbeat_video.js
https://vars.hotjar.com/rcj-9a8c65a25e627120fda741095c91ae72.html
http://s4.reutersmedia.net/resources_v3/images/r-generic-hdr.png
http://s2.reutersmedia.net/resources_v3/images/win-ico-search.png
http://static.yieldmo.com/ym.m3.js
http://s2.reutersmedia.net/resources_v3/js/libraries/jquery.cookie.js
http://pagead2.googlesyndication.com/pagead/osd.js
http://s3.reutersmedia.net/resources_v3/css/win-main.css
http://s2.reutersmedia.net/resources_v3/images/win-menu-open-bg.gif
https://gum.criteo.com/sync?r=2&c=160&j=_ccb
http://s4.reutersmedia.net/resources_v3/images/win-sprite-follow.png
http://s3.reutersmedia.net/resources_v3/js/libraries/jquery.min.js
https://securepubads.g.doubleclick.net/gpt/pubads_impl_107.js
http://s4.reutersmedia.net/resources_v3/images/win-ico-menu.png
http://www.google-analytics.com/analytics.js
http://s4.reutersmedia.net/resources_v3/images/win-close-banner.png
https://idsync.rlcdn.com/397286.gif?partner_uid=578de3cb2191c4221808
http://pixel.adsafeprotected.com/jload?anId=10764&campId=300x250&pubId=48816672&chanId=11591472&placementId=129708792&pubCreative=96724672152&pubOrder=401817312&custom=mobile_hp_mpu
https://static.yieldmo.com/blank.min.html?orig=http://mobile.reuters.com
http://fast.reuters.demdex.net/dest5.html?d_nsid=0
http://s2.reutersmedia.net/resources_v3/images/search-input-close.png
https://static.yieldmo.com/sdk/template/js/23.handlebars.js
http://tpc.googlesyndication.com/safeframe/1-0-5/html/container.html
http://s2.reutersmedia.net/resources_v3/js/win-wire.js
https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjsucTGZ2DkEEcU3yjPjRh6wEkSv4g2wsxiTBIBWbzzrybWzSeR2XQbb0HVsIJQmiJeKrJb3Jf7n8Aqq9mXHTDvfhjzNvy3z3sy639e4FksPVg4pUZMgGGOPZSkOisOgm1iCN4YPzmXA9Qk7KH5xejzNbKvG8a9Y6AtYvzhxuzXs6WO2PnDapEuRymm4s5GFiEtVbxJjog-C147Fg_Kw_WOtspxlnkjup2p16tVrfvGoM10Q1KEFaZ3v8ynKlmGhQWwq46Ydw43o&sig=Cg0ArKJSzP7Eg_PUPiiAEAE&urlfix=1&adurl=
http://www.reuters.com/assets/breakingNews?view=json&sp=drawBreakingNews
