https://officehome.msocdn.com/css/webfonts/SegoeUI-Light-final.ttf
https://c.microsoft.com/ms.js
https://officehome.msocdn.com/s/61e0ce5d/Areas/Home/Content/js/build/bundles/unauthstaticstyles.css
https://officehome.msocdn.com/css/webfonts/SegoeUI-Bold-final.woff
https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=ACT-Web-JS-2.7.1&x-apikey=ea6758984c4b43529f9929667d8d3198-c52d4a8b-47fe-4fdf-99b8-5f897ff4e33b-7365
https://officehome.msocdn.com/s/ac46a418/Areas/Home/Content/js/build/bundles/unauthhomepage.js
https://officehome.msocdn.com/js/jquery.appear.js
https://officehome.msocdn.com/css/webfonts/SegoeUI-Regular-final.ttf
https://c1.microsoft.com/c.gif?DI=4050&did=1&t=
https://officehome.msocdn.com/js/UnauthAriaLogging.js
https://officehome.msocdn.com/images/home4-sprite.png
https://officehome.msocdn.com/s/4fc774a3/images/google-play-badge.png
https://www.office.com/
https://officehome.msocdn.com/js/unauthHomeFeedback.js
https://officehome.msocdn.com/css/webfonts/SegoeUI-Regular-final.woff
https://officehome.msocdn.com/css/webfonts/SegoeUI-Light-final.woff
https://officehome.msocdn.com/css/webfonts/SegoeUI-SemiBold-final.woff
https://officehome.msocdn.com/Areas/Home/Content/js/ext/aria/2.7.1/aria-web-telemetry-2.7.1.js
https://officehome.msocdn.com/JS/wedcs.js
https://officehome.msocdn.com/s/908fce3c/images/home4-hero-mobile.jpg
https://officehome.msocdn.com/css/webfonts/SegoeUI-SemiBold-final.ttf
https://officehome.msocdn.com/s/39b6fc28/images/desktop_office.png
https://officehome.msocdn.com/js/jquery-1.11.3.min.js
