http://cdn.thepennyhoarder.com/wp-includes/js/jquery/jquery-migrate.min.js.gzip
http://srv-2017-06-04-00.config.parsely.com/config/thepennyhoarder.com
http://cdn.thepennyhoarder.com/wp-content/plugins/flight-by-canto/assets/js/frontend.min.js.gzip
http://tag.bounceexchange.com/848/i.js
http://www.thepennyhoarder.com/wp-content/themes/thepennyhoarder/js/bootstrap.min.js?v3_6
http://fonts.gstatic.com/s/roboto/v15/Hgo13k-tfSpn0qi1SFdUfZBw1xU1rKptJj_0jans920.woff2
http://www.google-analytics.com/analytics.js
http://cdn.thepennyhoarder.com/wp-content/themes/thepennyhoarder/images/footer_taylormedia.png
http://cdn.thepennyhoarder.com/wp-content/plugins/jetpack/css/jetpack.css.gzip
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/12150000/sturti-370x208.jpg
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/13150000/laflor-772x436.jpg
http://fonts.gstatic.com/s/roboto/v15/RxZJdnzeo3R5zSexge8UUZBw1xU1rKptJj_0jans920.woff2
http://fonts.gstatic.com/s/roboto/v15/mnpfi9pxYH-Go5UiibESIpBw1xU1rKptJj_0jans920.woff2
http://cdn.thepennyhoarder.com/wp-content/plugins/flight-by-canto/assets/css/frontend.css.gzip
http://widgets.outbrain.com/outbrain.js
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/14160543/16764975893_ffd4e468b5_o-772x436.jpg
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/12150000/GettyImages-503001786-1-370x208.jpg
http://cdn.thepennyhoarder.com/wp-content/themes/thepennyhoarder/images/search.png
http://cdn.thepennyhoarder.com/wp-content/themes/thepennyhoarder/css/fonts.googleapis.roboto.cached.css
http://cdn.thepennyhoarder.com/wp-includes/js/jquery/jquery.js.gzip
http://b.scorecardresearch.com/beacon.js
http://staticxx.facebook.com/connect/xd_arbiter/r/D6ZfFsLEB4F.js?version=42
http://fonts.gstatic.com/s/roboto/v15/oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0A.woff2
http://fonts.gstatic.com/s/robotocondensed/v13/Zd2E9abXLFGSr9G3YK2MsH4vxAoi6d67T_UKWi0EoHQ.woff2
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/13150000/Daviles-370x208.jpg
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/12150000/jetblue-370x208.jpg
http://aff939e759ffc58fd9987988a7e804e28.profile.bom52.cloudfront.net/test.png
http://static.parsely.com/p.js
http://fonts.gstatic.com/s/robotoslab/v6/dazS1PrQQuCxC3iOAJFEJf79_ZuUxCigM2DespTnFaw.woff2
http://www.thepennyhoarder.com/wp-content/themes/thepennyhoarder/style.css
http://www.thepennyhoarder.com/wp-content/themes/thepennyhoarder/css/bootstrap.css?v3_6
http://www.thepennyhoarder.com/wp-content/themes/thepennyhoarder/images/mobile-bg.jpg
https://staticxx.facebook.com/connect/xd_arbiter/r/D6ZfFsLEB4F.js?version=42
http://fonts.gstatic.com/s/roboto/v15/d-6IYplOFocCacKzxwXSOJBw1xU1rKptJj_0jans920.woff2
https://connect.facebook.net/en_US/fbevents.js
http://cdn.thepennyhoarder.com/wp-content/themes/thepennyhoarder/images/inlineLogo.png
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/13150000/GettyImages-470795280-370x208.jpg
http://www.thepennyhoarder.com/wp-content/themes/thepennyhoarder/fonts/icomoon.woff?-keuaaf
http://tools.thepennyhoarder.com/?nofavicon&get_share_count=http://www.thepennyhoarder.com/home/
http://cdn.thepennyhoarder.com/wp-content/plugins/tph-top-bar-news-ticker/scripts/jquery.newsTicker.min.js.gzip
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/12124647/carson_091516-370x208.jpg
http://connect.facebook.net/en_US/sdk.js
https://d31qbv1cthcecs.cloudfront.net/atrk.js
http://edge.quantserve.com/quant.js
http://cdn.thepennyhoarder.com/wp-content/themes/thepennyhoarder/images/footer_aug2016.png
http://www.thepennyhoarder.com/
http://www.thepennyhoarder.com/wp-content/themes/thepennyhoarder/theme.css?v1484151676
http://s0.wp.com/wp-content/js/devicepx-jetpack.js
http://www.thepennyhoarder.com/wp-content/themes/thepennyhoarder/js/customJS.js?v1484151676
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/13162536/trader-joes_small-772x436.jpg
http://stats.wp.com/e-201702.js
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/13150000/Chalk_1-370x208.jpg
http://cdn.thepennyhoarder.com/wp-content/plugins/tph-general-functions/tph_custom_styles.css.gzip
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/13182950/tedmurphyjpg-370x208.jpg
http://www.thepennyhoarder.com/wp-content/themes/thepennyhoarder/js/jquery.main.js
http://cdn.thepennyhoarder.com/wp-content/uploads/2017/01/13150000/AP_walmart-772x436.jpg
http://www.thepennyhoarder.com/wp-content/themes/thepennyhoarder/js/numeral.js
