http://cdn.taboola.com/libtrc/wixcom-sc/tfa.js
http://www.google-analytics.com/analytics.js
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/features.jpg
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/banner/play.svg
https://www.youtube.com/ad_data_204
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/bower_components/load-experiments-sync/dist/scripts/scripts.js
https://static.doubleclick.net/instream/ad_status.js
https://s.ytimg.com/yts/jsbin/www-widgetapi-vflhwduOt/www-widgetapi.js
https://www.youtube.com/embed/YrERmaDZNl0?rel=0&showinfo=0&theme=light&enablejsapi=1&origin=http%3A%2F%2Fwww.wix.com&widgetid=1
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/bower_components/wix-header-and-footer/dist/images/logos/menu.svg?1484650994
https://s.ytimg.com/yts/jsbin/www-embed-player-vflkQkm9I/www-embed-player.js
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/bower_components/wix-header-and-footer/dist/styles/svg-font/header-and-footer-svg-font-icons.woff
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/footer/inst.svg
http://www.wix.com/_api/wix-laboratory-server/laboratory/conductAllInScope?scope=homepage&accept=jsonp&callback=experiments.addJsonp
http://www.wix.com/_Incapsula_Resource?SWJIYLWA=2977d8d74f63d7f8fedbea018b7a1d05&ns=1
http://connect.facebook.net/en_US/fbevents.js
http://static.parastorage.com/services/third-party/fonts/Helvetica/Fonts/530dee22-e3c1-4e9f-bf62-c31d510d9656.woff
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/bower_components/jquery/jquery.js
https://js-agent.newrelic.com/nr-998.min.js
https://www.google.com/js/bg/v-7aPSHvqGXfhg1YmMcqoXwpwb8Q9v1ozse_-Vy-500.js
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/bower_components/wix-header-and-footer/dist/images/logos/WixlogoMobile.svg?1484650994
http://www.wix.com/_api/wix-laboratory-server/laboratory/conductAllInScope?scope=users&accept=jsonp&callback=experiments.addJsonp
https://s.ytimg.com/yts/imgbin/player-cougar-2x-vflABVaG6.png
https://googleads.g.doubleclick.net/pagead/id
http://static.parastorage.com/services/third-party/fonts/Helvetica/fontFace.css
http://static.parastorage.com/services/third-party/fonts/Helvetica/Fonts/50d35bbc-dfd4-48f1-af16-cf058f69421d.woff
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/player/video-preview.jpg?1484663537
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/bower_components/wix-header-and-footer/dist/styles/header.css
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/bower_components/wix-header-and-footer/dist/scripts/scripts.js
https://www.youtube.com/embed/bcrrxRk-YeQ?rel=0&showinfo=0&theme=light&enablejsapi=1&origin=http%3A%2F%2Fwww.wix.com&widgetid=2
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/ai-look-alike-mobile.jpg?1484663536
https://script.hotjar.com/modules-5d19873aea85cbea800b9bffe46ced81.js
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/styles/main.css
http://static.hotjar.com/c/hotjar-147814.js?sv=5
http://www.wix.com/
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/footer/google.svg
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/everything.jpg
http://script.crazyegg.com/pages/scripts/0013/2477.js?415706
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/banner/close.svg
https://s.ytimg.com/yts/cssbin/www-embed-player-sprite-mode-2x-vfl-mbExy.css
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/scripts/scripts.js
https://vars.hotjar.com/rcj-9a8c65a25e627120fda741095c91ae72.html
http://static.parastorage.com/services/third-party/fonts/Helvetica/Fonts/bcf54343-d033-41ee-bbd7-2b77df3fe7ba.woff
https://www.youtube.com/iframe_api
http://www.wix.com/_api/wix-laboratory-server/laboratory/conductAllInScope?scope=marketing&accept=jsonp&callback=experiments.addJsonp
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/footer/facebook.svg
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/scripts/modules.js
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/footer/pin.svg
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/mobile-header.jpg?1484663537
http://www.googletagmanager.com/gtm.js?id=GTM-MDD5C4
https://s.ytimg.com/yts/jsbin/player-en_US-vflbh8HdB/base.js
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/footer/tw.svg
https://i.ytimg.com/vi/YrERmaDZNl0/hqdefault.jpg
http://fast.fonts.com/t/1.css?apiType=css&projectid=33bd0973-5b82-45be-bb77-837225874dfe
http://www.googleadservices.com/pagead/conversion_async.js
http://static.parastorage.com/services/wix-homepage-davinci-mobile/1.60.0/images/footer/in.svg
https://www.google.com/ads/user-lists/1041825691/?label=FYMYCO-T6gMQm__j8AM&fmt=3&num=1&cv=8&frm=0&url=http%3A%2F%2Fwww.wix.com%2F&random=3164988097&fpvtc=/1041825691/%3Frandom%3D856806928%26cv%3D8%26fst%3D1484719200000%26num%3D1%26fmt%3D3%26label%3DFYMYCO-T6gMQm__j8AM%26guid%3DON%26u_h%3D732%26u_w%3D412%26u_ah%3D732%26u_aw%3D412%26u_cd%3D32%26u_his%3D2%26u_tz%3D-300%26u_java%3Dfalse%26u_nplug%3D0%26u_nmime%3D0%26frm%3D0%26url%3Dhttp://www.wix.com/%26tiba%3DFree%2520Website%2520Builder%2520%257C%2520Create%2520a%2520Free%2520Website%2520%257C%2520WIX.com%26async%3D1
http://static.parastorage.com/services/third-party/fonts/Helvetica/Fonts/60be5c39-863e-40cb-9434-6ebafb62ab2b.woff
http://www.wix.com/_api/wix-laboratory-server/laboratory/conductAllInScope?scope=headerAndFooter
https://i.ytimg.com/vi/bcrrxRk-YeQ/hqdefault.jpg
